[package]
name = "risifetch"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
systemstat = "0.1"
nix = "0.23"
